name: Build VST - All Platforms

on:
  push:
    branches: [main, test-gcc-pyinstaller]
  pull_request:
    branches: [main, test-gcc-pyinstaller]

permissions:
  contents: write
  actions: read
  pull-requests: write

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup MSVC
        uses: microsoft/setup-msbuild@v1

      - name: Configure CMake
        working-directory: vst
        run: |
          cmake -B build -G "Visual Studio 17 2022" -A x64 -DCMAKE_BUILD_TYPE=Release

      - name: Build
        working-directory: vst
        run: |
          cmake --build build --config Release

      - name: Upload Windows VST
        uses: actions/upload-artifact@v4
        with:
          name: ObsidianNeural-Windows-VST3
          path: vst/build/ObsidianNeuralVST_artefacts/Release/VST3/

  build-macos:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install dependencies
        run: |
          brew install cmake ninja

      - name: Configure CMake
        working-directory: vst
        run: |
          cmake -B build -G Ninja -DCMAKE_BUILD_TYPE=Release

      - name: Build
        working-directory: vst
        run: |
          cmake --build build --config Release

      - name: Upload macOS VST
        uses: actions/upload-artifact@v4
        with:
          name: ObsidianNeural-macOS-VST3
          path: vst/build/ObsidianNeuralVST_artefacts/Release/VST3/

  build-linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            cmake ninja-build \
            libasound2-dev \
            libx11-dev libxext-dev libxrandr-dev libxcomposite-dev \
            libxinerama-dev libxcursor-dev \
            libfreetype6-dev \
            libfontconfig1-dev \
            libgtk-3-dev \
            libwebkit2gtk-4.1-dev \
            libcurl4-openssl-dev

      - name: Configure CMake
        working-directory: vst
        run: |
          cmake -B build -G Ninja -DCMAKE_BUILD_TYPE=Release

      - name: Build
        working-directory: vst
        run: |
          cmake --build build --config Release

      - name: Upload Linux VST
        uses: actions/upload-artifact@v4
        with:
          name: ObsidianNeural-Linux-VST3
          path: vst/build/ObsidianNeuralVST_artefacts/Release/VST3/

  build-python-executables:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            name: linux
          - os: windows-latest
            name: windows
          - os: macos-latest
            name: macos

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        shell: bash
        run: |
          pip install pillow
          if [[ "${{ matrix.name }}" == "windows" ]]; then
            choco install mingw
          fi
          git clone https://github.com/pyinstaller/pyinstaller.git
          cd pyinstaller
          if [[ "${{ matrix.name }}" == "windows" ]]; then
            export PATH="/c/tools/mingw64/bin:$PATH"
            cd bootloader && python ./waf distclean all --gcc && cd ..
          else
            cd bootloader && python ./waf distclean all && cd ..
          fi
          pip install .
          cd ..

      - name: Convert logo to platform icons
        shell: bash
        run: |
          python -c "
          from PIL import Image
          import sys

          img = Image.open('logo.png').convert('RGBA')
          img = img.resize((512, 512), Image.Resampling.LANCZOS)

          if sys.platform == 'win32':
              img.save('logo.ico', format='ICO', sizes=[(16,16), (32,32), (48,48), (64,64), (128,128), (256,256)])
          elif sys.platform == 'darwin':
              img.save('logo_temp.png')
          else:
              pass
          "

      - name: Create ICNS for macOS
        if: matrix.name == 'macos'
        run: |
          sips -s format icns logo_temp.png --out logo.icns

      - name: Build executables with icons
        shell: bash
        run: |
          pyinstaller --onefile --name obsidian-server-${{ matrix.name }} server_interface.py
          pyinstaller --onefile --name obsidian-installer-${{ matrix.name }} installer.py

      - name: Upload Python executables
        uses: actions/upload-artifact@v4
        with:
          name: ObsidianNeural-Python-${{ matrix.name }}
          path: dist/

  commit-binaries:
    needs: [build-python-executables]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT_TOKEN }}
          fetch-depth: 0

      - name: Download all Python artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: ObsidianNeural-Python-*
          merge-multiple: false

      - name: Organize binaries
        run: |
          mkdir -p bin

          if [ -d "ObsidianNeural-Python-windows" ]; then
            cp ObsidianNeural-Python-windows/obsidian-server-windows.exe bin/OBSIDIAN-Neural-Server.exe
          fi

          if [ -d "ObsidianNeural-Python-macos" ]; then
            cp ObsidianNeural-Python-macos/obsidian-server-macos bin/OBSIDIAN-Neural-Server-macos
          fi

          if [ -d "ObsidianNeural-Python-linux" ]; then
            cp ObsidianNeural-Python-linux/obsidian-server-linux bin/OBSIDIAN-Neural-Server-linux
          fi

      - name: Commit binaries
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add bin/
          git commit -m "Update binaries [skip ci]" || exit 0
          git push

  create-release:
    needs:
      [
        build-windows,
        build-macos,
        build-linux,
        build-python-executables,
        commit-binaries,
      ]
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT_TOKEN }}

      - name: Download all artifacts
        uses: actions/download-artifact@v4

      - name: Create release assets
        run: |
          if [ -d "ObsidianNeural-Windows-VST3" ]; then
            cd ObsidianNeural-Windows-VST3
            zip -r ../OBSIDIAN-Neural-Windows-VST3.zip .
            cd ..
          fi

          if [ -d "ObsidianNeural-macOS-VST3" ]; then
            cd ObsidianNeural-macOS-VST3
            zip -r ../OBSIDIAN-Neural-macOS-VST3.zip .
            cd ..
          fi

          if [ -d "ObsidianNeural-Linux-VST3" ]; then
            cd ObsidianNeural-Linux-VST3
            tar -czf ../OBSIDIAN-Neural-Linux-VST3.tar.gz .
            cd ..
          fi

          if [ -d "ObsidianNeural-Python-windows" ]; then
            cp ObsidianNeural-Python-windows/obsidian-installer-windows.exe ./OBSIDIAN-Neural-Installer-Windows.exe
          fi

          if [ -d "ObsidianNeural-Python-macos" ]; then
            cp ObsidianNeural-Python-macos/obsidian-installer-macos ./OBSIDIAN-Neural-Installer-macOS
          fi

          if [ -d "ObsidianNeural-Python-linux" ]; then
            cp ObsidianNeural-Python-linux/obsidian-installer-linux ./OBSIDIAN-Neural-Installer-Linux
          fi

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ github.run_number }}
          name: "OBSIDIAN-Neural v${{ github.run_number }}"
          body: |
            ## 🎵 OBSIDIAN-Neural Release v${{ github.run_number }}

            ### 📥 Quick Install
            Download the installer for your platform and run it:
            - **Windows**: `OBSIDIAN-Neural-Installer-Windows.exe` (run as admin)
            - **macOS**: `OBSIDIAN-Neural-Installer-macOS` 
            - **Linux**: `OBSIDIAN-Neural-Installer-Linux`

            ### 🎛️ VST3 Plugins (for DAWs)
            - **Windows**: `OBSIDIAN-Neural-Windows-VST3.zip`
            - **macOS**: `OBSIDIAN-Neural-macOS-VST3.zip`
            - **Linux**: `OBSIDIAN-Neural-Linux-VST3.tar.gz`

            ---

            ## 🍎 macOS Installation

            **Important:** This plugin is not yet Apple-signed as it's an independent open source project in development.

            ### For VST3 Plugin:
            1. **Download** `OBSIDIAN-Neural-macOS-VST3.zip` and extract it
            2. **Open Terminal** (search "Terminal" in Spotlight)
            3. **Run this command** (copy-paste and press Enter):
               ```bash
               xattr -c ~/Downloads/OBSIDIAN-Neural.vst3
               ```
               *(Adjust path if file is elsewhere)*
            4. **Install plugin:** Drag `OBSIDIAN-Neural.vst3` to:
               ```
               /Library/Audio/Plug-Ins/VST3/
               ```
               💡 **Tip:** In Finder, press `Cmd+Shift+G` and paste this path
            5. **If your DAW won't load the plugin:**
               - **System Settings** → **Privacy & Security**
               - **Scroll down** to see OBSIDIAN-Neural message
               - **Click "Open Anyway"** and confirm
            6. **Restart your DAW** - plugin will appear in VST3 instruments

            ### Why these steps?
            Apple requires developers to pay $99/year for code signing. As an independent open source project, we prioritize free development for now. Official signing may come based on project evolution.

            **⚠️ Having issues?** Please mention your macOS version when reporting problems.
            ---

            ### 🔄 Changes
            - Built from commit ${{ github.sha }}
            - Auto-generated from GitHub Actions
          files: |
            OBSIDIAN-Neural-Installer-*.exe
            OBSIDIAN-Neural-Installer-macOS
            OBSIDIAN-Neural-Installer-Linux
            OBSIDIAN-Neural-*-VST3.*
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
